version: "3.9"
services:
  web:
    build: .
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0.21
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro